namespace GTA3SaveEditor.Core.Game
{
    public enum ModelIndex
    {
        // thanks re3! :-D

        PLAYER = 0,
        COP,
        SWAT,
        FBI,
        ARMY,
        MEDIC,
        FIREMAN,
        MALE01,
        TAXI_D,
        PIMP,
        GANG01,
        GANG02,
        GANG03,
        GANG04,
        GANG05,
        GANG06,
        GANG07,
        GANG08,
        GANG09,
        GANG10,
        GANG11,
        GANG12,
        GANG13,
        GANG14,
        CRIMINAL01,
        CRIMINAL02,
        SPECIAL01,
        SPECIAL02,
        SPECIAL03,
        SPECIAL04,
        MALE02,
        MALE03,
        FATMALE01,
        FATMALE02,
        FEMALE01,
        FEMALE02,
        FEMALE03,
        FATFEMALE01,
        FATFEMALE02,
        PROSTITUTE,
        PROSTITUTE2,
        P_MAN1,
        P_MAN2,
        P_WOM1,
        P_WOM2,
        CT_MAN1,
        CT_MAN2,
        CT_WOM1,
        CT_WOM2,
        LI_MAN1,
        LI_MAN2,
        LI_WOM1,
        LI_WOM2,
        DOCKER1,
        DOCKER2,
        SCUM_MAN,
        SCUM_WOM,
        WORKER1,
        WORKER2,
        B_MAN1,
        B_MAN2,
        B_MAN3,
        B_WOM1,
        B_WOM2,
        B_WOM3,
        MOD_MAN,
        MOD_WOM,
        ST_MAN,
        ST_WOM,
        FAN_MAN1,
        FAN_MAN2,
        FAN_WOM,
        HOS_MAN,
        HOS_WOM,
        CONST1,
        CONST2,
        SHOPPER1,
        SHOPPER2,
        SHOPPER3,
        STUD_MAN,
        STUD_WOM,
        CAS_MAN,
        CAS_WOM,
        BUSKER1,
        BUSKER2,
        BUSKER3,
        BUSKER4,
        // three more peds possible

        LAST_PED = 89,
        FIRST_VEHICLE,

        LANDSTAL = FIRST_VEHICLE,
        IDAHO,
        STINGER,
        LINERUN,
        PEREN,
        SENTINEL,
        PATRIOT,
        FIRETRUCK,
        TRASH,
        STRETCH,
        MANANA,
        INFERNUS,
        BLISTA,
        PONY,
        MULE,
        CHEETAH,
        AMBULAN,
        FBICAR,
        MOONBEAM,
        ESPERANT,
        TAXI,
        KURUMA,
        BOBCAT,
        MRWHOOP,
        BFINJECT,
        CORPSE,
        POLICE,
        ENFORCER,
        SECURICA,
        BANSHEE,
        PREDATOR,
        BUS,
        RHINO,
        BARRACKS,
        TRAIN,
        CHOPPER,
        DODO,
        COACH,
        CABBIE,
        STALLION,
        RUMPO,
        RCBANDIT,
        BELLYUP,
        MRWONGS,
        MAFIA,
        YARDIE,
        YAKUZA,
        DIABLOS,
        COLUMB,
        HOODS,
        AIRTRAIN,
        DEADDODO,
        SPEEDER,
        REEFER,
        PANLANT,
        FLATBED,
        YANKEE,
        ESCAPE,
        BORGNINE,
        TOYZ,
        GHOST,

        GRENADE = 170,
        AK47,
        BASEBALL_BAT,
        COLT,
        MOLOTOV,
        ROCKETLAUNCHER,
        SHOTGUN,
        SNIPER,
        UZI,
        MISSILE,
        M16,
        FLAMETHROWER,
        BOMB,
        FINGERS,

        CUTOBJ01 = 185,
        CUTOBJ02,
        CUTOBJ03,
        CUTOBJ04,
        CUTOBJ05,

        CAR_DOOR = 190,
        CAR_BUMPER,
        CAR_PANEL,
        CAR_BONNET,
        CAR_BOOT,
        CAR_WHEEL,
        BODYPARTA,
        BODYPARTB,

        AIRTRAIN_VLO = 198,
        LOPOLYGUY,

        NUM_DEFAULT_MODELS
    };
}
